### ISSUE TITLE
Failed to run the tool inside the subdirectory

### ISSUE THREAD

**Issue by eight04** [eight04/userscript-meta-cli#2]
```
D:\Dev\textarea-plus\src>userscript-meta
module.js:559
    throw err;
    ^

Error: Cannot find module 'D:\Dev\textarea-plus\src/package.json'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at packageToMeta (D:\Dev\userscript-meta-builder\index.js:1:92)
    at Object.<anonymous> (D:\Dev\userscript-meta-builder\cli.js:36:22)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
```

Need a better way to lookup `package.json`.

**Comment by eight04** [comment]
Fixed in 0.3.0.
